---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```

# expppel

<!-- badges: start -->
<!-- badges: end -->

Prepare cartridge case x3p scans for comparison.

## Installation

You can install the development version of expppel like so:

``` r
# install.packages("remotes")
remotes::install_github("jzemmels/expppel")
```

## Example

This is a basic example which shows you how to solve a common problem:

```{r example}
library(expppel)
data("K013sA1_raw")

attributes(K013sA1_raw)

# install.packages("impressions")
impressions::x3pPlot(K013sA1_raw)

# 3D rendering of scan surface + mask:
# install.packages("x3ptools")
# x3ptools::x3p_image(K013sA1_raw)
```

```{r}
# remove values based on mask
table(K013sA1_raw$mask) # mask contains mostly black and fewer white pixels

K013sA1_unmasked <- x3p_extract(K013sA1_raw,"#FFFFFFFF") # keep values associated with white mask elements
impressions::x3pPlot(K013sA1_unmasked,
                     x3p_trim_na(K013sA1_unmasked))
```


